### DISCUSSION TITLE
docker image with custom chainId

### DISCUSSION THREAD

**Discussion by success-0627** [ConsenSys-archive/ganache#3062] [General]
![image](https://user-images.githubusercontent.com/53897531/168335025-9e070671-38dd-403a-9d4b-c54001591c21.png)

![image](https://user-images.githubusercontent.com/53897531/168335074-4af3314e-aa37-4775-9d2e-72cf974c7cc3.png)

If I remove `- "--chain.chainId 56"` / `- --chain.chainId 56` / `- "--chain.chainId=56"`, everything is ok.

**Comment by success-0627** [comment]
PS: this is what I tried inside of my custom docker composer.
![image](https://user-images.githubusercontent.com/53897531/168335382-5e5b3816-12bc-4dab-a298-a11e3d953f34.png)

**Comment by davidmurdoch** [comment]
I don't think that is how use the docker compose `command` option. See their docs here: https://docs.docker.com/compose/compose-file/compose-file-v3/#command

**Comment by success-0627** [comment]
I tried with that too. same error

**Reply by cds-amal** [reply]
> I tried with that too. same error

I also tried @davidmurdoch 's suggestion, which is
```yml
ganache:
  image: trufflesuite/ganache:latest
  restart: on-failure
  ports:
    - "8545:8545"
  command: [ "--chain.chainId",  "56", "-e", "1000000" ]
```

## Screencast
<a href="https://asciinema.org/a/J177Nbn9Yx2Z4muLuzcElXKq1?autoplay=1"><img src="https://asciinema.org/a/J177Nbn9Yx2Z4muLuzcElXKq1.png" width="836"/></a>
