### ISSUE TITLE
Ganache-cli still faster (forking bsc on mac m1)

### ISSUE THREAD

**Issue by NikZak** [ConsenSys-archive/ganache#2178]
Ok, this is a post of help. I want to figure whether this is just my problem. 
I tried 
ganache-cli
ganache-7-alpha
ganache-7-beta
ganache-7
hardhat

And I always go back to ganache-cli eventually as it is the fastest and most stable and the only one that let a long chain of operations run till the end. I don't know whether the problem is in my config or smth else as ganache is notoriously hard to debug based on the logs alone. 

I'll probably post a config for my ganache-cli and ganache-7 to get feedback if there are any major mistakes. And would be happy to hear anyone else - what is their experience.

ganache-cli
```
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --host 0.0.0.0 -f "https://bsc-dataseed1.defibit.io/" --chainId 1337 --account "smthsmth,100000000000000000000" --account "smthsmth,100000000000000000000"
    ports:
      - "8545:8545"
```
ganache-7
```
  ganache:
    image: trufflesuite/ganache:v7.0.0
    command: --host 0.0.0.0 -f "https://bsc-dataseed1.defibit.io/"  --chain.chainId 1337 --account "smthsmth,100000000000000000000" --account "smthsmth,100000000000000000000"
    ports:
      - "8545:8545"

```

Thank you and any feedback is welcome!
