### ISSUE TITLE
"Unknown argument: ganache" error when trying run ganache 7 using docker-compose file

### ISSUE THREAD

**Issue by mikemcclaran** [ConsenSys-archive/ganache#2254]
Prior to v7, I was able to use ganache-cli to run ganache in docker container using this docker-compose file
```

version: "3.8"

volumes:
  ganache:

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    volumes:
      - ganache:/app/chaindb
    ports:
      - "9545:9545"
    command:
      ganache-cli
  
```

for v7, I changed my docker-compose file to the following
```
version: "3.8"

volumes:
  ganache:

services:
  ganache:
    image: trufflesuite/ganache:latest
    volumes:
      - ganache:/app/chaindb
    ports:
      - "9545:9545"
    command:
      ganache

```
However, when attempting to start the container, I get the following message `Unknown argument: ganache`

**Comment by davidmurdoch** [comment]
Ganache now validates the arguments passed to its executable, whereas previously it did not.

Both the `trufflesuite/ganache-cli` and the `trufflesuite/ganache` images automatically run a command when started (like when you run `docker-compose up`), so `ganache-cli` and `ganache` end up getting passed as command-line _options_ to the Docker container's `ENTRYPOINT` (basically just calling `ganache` with no options).

So you are effectively attempting to run `$ ganache ganache` here, which isn't allowed.

Remove the `command: ganache` lines and you should be good to go.

Note: you can the `command` section to pass any of the ganache options you'd like, e.g., `--port 9545`:

```yaml
version: "3.8"

volumes:
  ganache:

services:
  ganache:
    image: trufflesuite/ganache:latest
    volumes:
      - ganache:/app/chaindb
    ports:
      - "9545:9545"
    command:
      --port 9545
```
      
Let us know if this gets things working for you (and feel free to Close the issue if it does)!
