### ISSUE TITLE
Ganache does not return a detailed exception

### ISSUE THREAD

**Issue by dminglv** [ConsenSys-archive/ganache#2935]
Hi! I found an error that Ganache does not return a detailed exception when calling contract function.

I use Ganache in Docker `trufflesuite/ganache:v7.0.4`

And Run it how:

```
version: '3.7'

services:
  ganache:
    image: trufflesuite/ganache:v7.0.4
    restart: always
    volumes:
      - ./blockchain-data:/blockchain-data
    env_file:
      - .env
    ports:
      - "8545:8545"
    command:
      --database.dbPath=/blockchain-data --miner.blockGasLimit=0x3B9ACA00 --port 8545
      --account="0x${TEST_CLOUD_ACCOUNT_PRIVATE_KEY_1},1000000000000000000000000000"
      --account="0x${TEST_CLOUD_ACCOUNT_PRIVATE_KEY_2},1000000000000000000000000000"
      --account="0x${TEST_CLOUD_ACCOUNT_PRIVATE_KEY_3},1000000000000000000000000000"
```

Everything works, but does not return a detailed exception error when calling the contract.

What do I get instead of getting a **Time Limit** exception:

`AssertionError: Expected transaction to be reverted with Time limit, but other exception was thrown: Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (error={"name":"ProviderError","code":-32000,"_isProviderError":true,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a54696d65206c696d697400000000000000000000000000000000000000000000"}, data="0x", code=CALL_EXCEPTION, version=providers/5.6.4)`

P.s in old package `trufflesuite/ganache-cli` everything works fine and I get a detailed error!
