### ISSUE TITLE
Ganache image options in Github Actions

### ISSUE THREAD

**Issue by tylde** [ConsenSys-archive/ganache#3004]
Hello, I would like to use ganache image as service container in github actions.
I cannot find how to apply options like `--wallet.seed`. Is it possible?

My current configuration:
```
jobs:
  job:
    services:
      ganache:
        image: trufflesuite/ganache:latest
        ports:
          - 8545:8545
        options: >-
          --name ganache
     steps:
     # ...
```
