### ISSUE TITLE
How to use `ganache` with `docker-compose`?

### ISSUE THREAD

**Issue by keinsell** [ConsenSys-archive/ganache#3595]
Are there any examples on starting ganache on docker-compose?

**Comment by keinsell** [comment]
Nevermind, figured it out by looking up source of `Dockerfile`

```yml
version: "3.7"
services:
  ganache:
    container_name: etherbridge-ganache
    image: trufflesuite/ganache:latest
    entrypoint: node /app/dist/node/cli.js -b 10 -a 5 --miner.coinbase 0x0E5079117F05C717CF0fEC43ff5C77156395F6E0 -m 'bacon hole season silly brave obscure arena another firm slide debris expand' --networkId 1337 --database.dbPath /ganache_data --fork.network rinkeby --fork.blockNumber 11261043
    ports:
      - "8545:8545"
    volumes:
      - ./.cache/ganache:/ganache_data
```
